## data_loader.R
## Load latest analysis dataset (Parquet preferred) and perform basic schema checks
## Author: Generated by assistant

# Auto-install missing packages
required_packages <- c("dplyr", "stringr", "purrr", "tidyr", "readr", "arrow")
missing_packages <- required_packages[!(required_packages %in% installed.packages()[,"Package"])]
if(length(missing_packages) > 0) {
  message("Installing missing packages: ", paste(missing_packages, collapse = ", "))
  install.packages(missing_packages, repos = "https://cloud.r-project.org")
}

suppressPackageStartupMessages({
  library(dplyr)
  library(stringr)
  library(purrr)
  library(tidyr)
  library(readr)
  library(arrow)
})

#' Find latest file by pattern in a directory
#' @param dir_path Directory to search
#' @param pattern Regex (e.g., '^final_analysis_.*\\.parquet$')
#' @return Character path or NA_character_
find_latest_file <- function(dir_path, pattern) {
  files <- list.files(dir_path, pattern = pattern, full.names = TRUE)
  if (length(files) == 0) return(NA_character_)
  info <- file.info(files)
  files[order(info$mtime, decreasing = TRUE)][1]
}

#' Load analysis dataset (Parquet preferred, fallback to Feather)
#' @param file_path Optional explicit path (.parquet or .feather/.fst)
#' @param outputs_dir Default notebooks/analysis_outputs (for input data only)
#' @return tibble
load_analysis_data <- function(
  file_path = NULL,
  outputs_dir = file.path(
    "/Users","suengj","Documents","Code","Python","Research","VC",
    "refactor_v2","notebooks","analysis_outputs"
  )
) {
  # Resolve file path
  if (is.null(file_path)) {
    parquet_path <- find_latest_file(outputs_dir, "^final_analysis_.*\\.parquet$")
    feather_path <- find_latest_file(outputs_dir, "^final_analysis_.*\\.(feather|fst)$")
    if (!is.na(parquet_path)) {
      file_path <- parquet_path
    } else if (!is.na(feather_path)) {
      file_path <- feather_path
    } else {
      stop("No final_analysis_*.parquet or .feather/.fst files found in: ", outputs_dir)
    }
  }
  
  # Read file
  ext <- tools::file_ext(file_path)
  message(sprintf("Loading analysis data: %s", file_path))
  if (tolower(ext) %in% c("parquet")) {
    df <- arrow::read_parquet(file_path)
  } else if (tolower(ext) %in% c("feather","fst")) {
    # arrow can read feather; fst not guaranteed here but pattern includes it just in case
    if (tolower(ext) == "feather") {
      df <- arrow::read_feather(file_path)
    } else {
      # Attempt via arrow; if not, instruct to convert upstream
      stop("Unsupported extension for loader: ", ext, ". Please export Feather/Parquet from Python.")
    }
  } else {
    stop("Unsupported file type: ", ext)
  }
  
  df <- tibble::as_tibble(df)
  
  # Coerce core keys and ensure presence
  if (!"firmname" %in% names(df)) stop("Column 'firmname' is required in dataset.")
  if (!"year" %in% names(df)) stop("Column 'year' is required in dataset.")
  
  df <- df %>%
    mutate(
      firmname = as.character(firmname),
      year = as.integer(year)
    )
  
  # Derive years_since_init if missing (derived variable, not in original data)
  if (!"years_since_init" %in% names(df)) {
    if ("initial_year" %in% names(df) && "year" %in% names(df)) {
      df <- df %>%
        mutate(years_since_init = as.integer(year - initial_year))
    } else {
      df <- df %>% mutate(years_since_init = NA_integer_)
    }
  }
  
  # Derive after7 if missing (derived variable, not in original data)
  if (!"after7" %in% names(df)) {
    df <- df %>%
      mutate(after7 = as.integer(!is.na(years_since_init) & years_since_init > 7))
  }
  
  df
}

#' Convenience: load and prepare analysis frame
#' @param file_path optional explicit path
#' @return tibble with all columns from the data file
load_and_prepare <- function(file_path = NULL) {
  df <- load_analysis_data(file_path = file_path)
  # Return all columns - no filtering
  df
}

# Data Loader for R Regression Analysis
# 
# This script loads preprocessed Parquet files created by the Python pipeline
# and prepares them for regression analysis in R.

library(arrow)
library(dplyr)
library(tidyr)

#' Load Parquet Data
#'
#' @param file_path Path to Parquet file
#' @return tibble
load_parquet_data <- function(file_path) {
  if (!file.exists(file_path)) {
    stop(paste("File not found:", file_path))
  }
  
  cat("Loading data from:", file_path, "\n")
  
  df <- read_parquet(file_path) %>%
    as_tibble()
  
  cat("Loaded:", nrow(df), "rows,", ncol(df), "columns\n")
  
  return(df)
}


#' Load CVC Analysis Data
#'
#' @param data_dir Directory containing processed data
#' @return tibble
load_cvc_data <- function(data_dir = "processed_data/cvc_analysis") {
  file_path <- file.path(data_dir, "final_data.parquet")
  
  df <- load_parquet_data(file_path)
  
  # Convert categorical variables to factors
  factor_cols <- c("leadVC", "coVC", "comname", "quarter")
  for (col in factor_cols) {
    if (col %in% colnames(df)) {
      df[[col]] <- as.factor(df[[col]])
    }
  }
  
  # Ensure numeric variables are numeric
  numeric_cols <- c("dgr_cent", "btw_cent", "pwr_p75", "pwr_p99", 
                    "constraint", "realized", "year")
  for (col in numeric_cols) {
    if (col %in% colnames(df)) {
      df[[col]] <- as.numeric(df[[col]])
    }
  }
  
  return(df)
}


#' Load Imprinting Analysis Data
#'
#' @param data_dir Directory containing processed data
#' @return tibble
load_imprinting_data <- function(data_dir = "processed_data/imprinting_analysis") {
  file_path <- file.path(data_dir, "panel_data.parquet")
  
  df <- load_parquet_data(file_path)
  
  # Convert categorical variables to factors
  df$firmname <- as.factor(df$firmname)
  
  # Ensure numeric variables are numeric
  numeric_cols <- c("year", "timesince", "dgr_cent", "btw_cent", 
                    "exitNum", "blau_index")
  for (col in numeric_cols) {
    if (col %in% colnames(df)) {
      df[[col]] <- as.numeric(df[[col]])
    }
  }
  
  return(df)
}


#' Summary Statistics
#'
#' @param df Data frame
#' @param variables Variables to summarize
print_summary_stats <- function(df, variables = NULL) {
  if (is.null(variables)) {
    variables <- colnames(df)[sapply(df, is.numeric)]
  }
  
  cat("\n========== Summary Statistics ==========\n\n")
  
  for (var in variables) {
    if (var %in% colnames(df)) {
      cat(var, ":\n")
      print(summary(df[[var]]))
      cat("\n")
    }
  }
}


# Example usage:
# cvc_data <- load_cvc_data()
# print_summary_stats(cvc_data, c("dgr_cent", "btw_cent", "realized"))

